version: '3.7'

services:
  app:
    build: ./docker
    container_name: "hotels_app"
    command: uvicorn main:app --reload --forwarded-allow-ips='*' --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:80"
    depends_on:
      - postgres
  postgres:
    container_name: "hotels_db"
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotels
    expose:
      - 5432
volumes:
  postgres_data: